# Generated by Django 2.2.2 on 2019-06-30 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("poems", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        )
    ]
