# Generated by Django 2.2.2 on 2019-07-06 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("poems", "0003_changepassword")]

    operations = [
        migrations.AddField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
