# Generated by Django 2.2.2 on 2019-07-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0004_changepassword_date")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-06 10:27", editable=False),
        )
    ]
