# Generated by Django 2.2.2 on 2019-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0006_auto_20190706_1803")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-06 19:10", editable=False),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
