# Generated by Django 2.2.2 on 2019-07-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("poems", "0009_auto_20190707_1049")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-07 10:51", editable=False),
        ),
        migrations.AlterField(
            model_name="rating",
            name="poem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="poems.Poem"
            ),
        ),
    ]
