# Generated by Django 2.2.2 on 2019-07-07 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("poems", "0010_auto_20190707_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-07 12:01", editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="rating", unique_together={("user", "poem")}
        ),
    ]
