# Generated by Django 2.2.2 on 2019-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0012_auto_20190707_1202")]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-08 20:11", editable=False),
        ),
    ]
