# Generated by Django 2.2.2 on 2019-07-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0014_auto_20190709_1853")]

    operations = [
        migrations.AddField(
            model_name="review",
            name="headline",
            field=models.CharField(default="a", max_length=64),
        ),
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-10 09:43", editable=False),
        ),
    ]
