# Generated by Django 2.2.2 on 2019-07-10 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("poems", "0016_auto_20190710_0944")]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-10 11:06", editable=False),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(
                choices=[
                    (1.0, "1.0"),
                    (2.0, "2.0"),
                    (3.0, "3.0"),
                    (4.0, "4.0"),
                    (5.0, "5.0"),
                ],
                decimal_places=1,
                max_digits=2,
            ),
        ),
    ]
