# Generated by Django 2.2.2 on 2019-07-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0017_auto_20190710_1107")]

    operations = [
        migrations.RenameField(
            model_name="poem", old_name="date", new_name="created_at"
        ),
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-11 11:06", editable=False),
        ),
    ]
