# Generated by Django 2.2.2 on 2019-07-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0019_auto_20190711_1253")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-11 13:38", editable=False),
        ),
    ]
