# Generated by Django 2.2.2 on 2019-07-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0020_auto_20190711_1338")]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="notification_status", new_name="read"
        ),
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-11 14:14", editable=False),
        ),
    ]
