# Generated by Django 2.2.2 on 2019-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0021_auto_20190711_1414")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-11 22:09", editable=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")],
                default="False",
                max_length=5,
            ),
        ),
    ]
