# Generated by Django 2.2.2 on 2019-07-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0022_auto_20190711_2209")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-11 22:23", editable=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
