# Generated by Django 2.2.3 on 2019-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0023_auto_20190711_2223")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-12 14:37", editable=False),
        )
    ]
