# Generated by Django 2.2.3 on 2019-07-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poems", "0024_auto_20190712_1437")]

    operations = [
        migrations.AlterField(
            model_name="changepassword",
            name="date",
            field=models.DateTimeField(default="2019-07-12 14:54", editable=False),
        )
    ]
