# Generated by Django 2.2.3 on 2019-07-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("poems", "0025_auto_20190712_1454")]

    operations = [migrations.RemoveField(model_name="changepassword", name="date")]
